config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index", page: :home
  get :privacy, to: "pages#index", page: :privacy

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  delete :logout, to: "sessions#destroy"
  get :layouts, to: "card_layouts#index"
  post "layout/change", to: "card_layouts#change"
  post :add, to: "resources#add"
  get :upload, to: "upload#index"
  delete :drop_resource, to: "upload#drop_resource"
  
  resources :shares do
    get :story
  end

  resources :cards do
    post :generate
    post :detach_music
    get :thumb
  end

  resources :resources do
    post :upload, on: :collection
    post :load, on: :collection
    post :insert, on: :collection
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
    before_action :signed_in?, only: [:create]
    def create
        @card = Card.find_by id: params[:card_id]
        if is_expired(@card.expired) || @card.code.nil?
            expi = 5.day.from_now
            share_name = Digest::SHA1.hexdigest("#{@card.user_id}|#{@card.id}|#{expi}")
            @card.update_attributes expired: expi, code: share_name
            res = ImageRenderService.render(@card, true, true)
            unless res.nil?
                @card.update_attributes data: res[1]
            end
        end
        unless @card.code.nil?
            ImageRenderService.render(@card, true, true)
        end
    end
    
    def show
        shared = false
        card = Card.find_by code: params[:id]

        redirect_to root_path and return unless card.present?

        unless valid_card? card, params[:id]
            Cloudinary::Uploader.destroy(card.code) unless card.code.nil?
            card.update_attributes code: nil, expired: nil
            redirect_to story_card
        end

        respond_to do |format|
            format.html
            format.png { send_data(open(card.data).read, {type: "image/png", disposition: "inline"})}
            format.mp4 { send_data(open(card.url).read, :disposition => 'inline', :stream => true) }
        end
    end

    def story
        @card = Card.find_by code: params[:share_id]
        redirect_to root_path and return unless @card.present?
        unless valid_card? @card, params[:share_id]
            Cloudinary::Uploader.destroy(@card.code) unless @card.code.nil?
            @card.update_attributes code: nil, expired: nil
            redirect_to root_path
        end
    end

    private
    def is_expired des_time
        return true if des_time.nil?
        return DateTime.now > des_time
    end

    def valid_card? card, token
        card_valid = Digest::SHA1.hexdigest("#{card.user.id}|#{card.id}|#{card.expired}")
        return card_valid.eql? token
    end
end

app/views/shares/_share_content.html.erb
<small class="mb-3">リンクをコピーして、共住します。</small>
    <div class="input-group px-3 mt-3">
    <input type="text" class="form-control jsShareData" value="<%= "#{share_story_url(share_id: card.code)}" %>">
    <div class="input-group-append">
        <button class="btn btn-primary jsCopyShareURL" type="button">コピー</button>
    </div>
    </div>
    <div class="share-social__list mt-3" >
    <a class="facebook jsFacebookShare" data-story="<%= share_story_url(share_id: card.code) %>" data-resource="<%= "#{share_url(id: card.code)}.png" %>"><i class="ti-facebook"></i></a>
    <a class="twitter jsTweet" data-story="<%= share_story_url(share_id: card.code) %>" data-resource="<%= "#{share_url(id: card.code)}.png" %>"><i class="ti-twitter"></i></a>
</div>

app/views/shares/_share_link_dialog.html.erb
<div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">シェア</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center jsShareModalBody">
        <% if card.code.nil? %>
          <div class="d-flex justify-content-center">
            <div class="spinner-border text-primary" role="status">
              <span class="sr-only"></span>
            </div>
          </div>
        <% else %>
          <%= render partial: "shares/share_content", locals:{ card: card }%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shares/create.js.erb
$('.jsShareModalBody').html('<%= j render partial:"shares/share_content", locals: {card: @card} %>')
$('.jsCopyShareURL').on('click', function(){
    var textBox = $(".jsShareData");
    textBox.select();
    document.execCommand("copy");
})
$('.jsFacebookShare').on('click', function(e){
        e.preventDefault()
        var source = $(this).data('story');
        FB.ui(
            {
                method: 'send',
                name: 'Xmeme Facebook share',
                href: source,
                link: source,
                picture: source,
                caption: 'Type your meme',
                description: 'Xmeme | Merry Chirstmas'
            },
            function (response) {
                if (response && response.post_id) {
                    
                } else {
                    
                }
            }
        );
    });
$('.jsTweet').on('click', function(e) {
    e.preventDefault();
    var story = $(this).data('story');
    var twitterWindow = window.open('https://twitter.com/share?url=' + story, 'twitter-popup', 'height=350,width=600');
    if(twitterWindow.focus) { twitterWindow.focus(); }
})

app/views/shares/story.html.erb
<% content_for :share_content do %>
    <meta property='og:image' content="<%= "#{share_url(id: @card.code)}.png" %>"/>
    <meta name="twitter:image" content="<%= "#{share_url(id: @card.code)}.png" %>" class="next-head"/>
<% end %>
<div class="story d-flex justify-content-center">
    <div class="snowflakes" aria-hidden="true">
        <div class="snowflake">❅</div>
        <div class="snowflake">❅</div>
        <div class="snowflake">❆</div>
        <div class="snowflake">❄</div>
        <div class="snowflake">❅</div>
        <div class="snowflake">❆</div>
        <div class="snowflake">❄</div>
        <div class="snowflake">❅</div>
        <div class="snowflake">❆</div>
        <div class="snowflake">❄</div>
    </div>
    <div class="story--bg" style="background: url(<%= "#{share_url(id: @card.code)}.png" %>); background-size: cover;"></div>
    <div class="story--content d-flex justify-content-lg-end">
        <div class="d-flex flex-row story--menu justify-content-end">
            <a class="action jsActionPlay playing"><i class="ti-control-play"></i></a>
            <% unless @card.url.nil? %>
                <%= link_to "#{share_url(id: @card.code)}.mp4",class:"action" do %><i class="ti-download"></i><% end %>
            <% end %>
        </div>
        <img class="story--image" src="<%= "#{share_url(id: @card.code)}.png" %>"/>
        <div class="progress story-progress">
            <div class="progress-bar bg-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
    <audio class="story-player" autoplay>
        <source class="jsAudioSource" src="<%= @card.try(:music).try(:container).try(:url) %>" type="audio/mp3">
    </audio>
    <div class="watermark text-center">
        <span class="md-b">Made with <i class="ti-heart"></i> by <%= @card.user.name %></span><br/><span class="pwd-b">Powered by <%= link_to "Xmeme", root_url %></span>
    </div>
</div>