config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index", page: :home
  get :privacy, to: "pages#index", page: :privacy

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  delete :logout, to: "sessions#destroy"
  get :layouts, to: "card_layouts#index"
  post "layout/change", to: "card_layouts#change"
  post :add, to: "resources#add"
  get :upload, to: "upload#index"
  delete :drop_resource, to: "upload#drop_resource"
  
  resources :shares do
    get :story
  end

  resources :cards do
    post :generate
    post :detach_music
    get :thumb
  end

  resources :resources do
    post :upload, on: :collection
    post :load, on: :collection
    post :insert, on: :collection
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
    def index
        @resource = Resource.new
        @layout_options = CardLayout.all.collect{|lyt| [lyt.name, lyt.id]}
        @resources = Resource.all
    end

    def drop_resource
        @resource = Resource.find_by id: params[:id]
        if @resource.present?
            @resource.destroy
            redirect_to upload_path
        end
    end
end

app/views/upload/index.html.erb
<%= form_for @resource, method: :post do |f| %>
    <div class="form-group">
        <%= f.label :container %>
        <%= f.file_field :container, multiple: false, class:"form-control-file" %>
    </div>
    <div class="form-group">
        <%= f.label :resource_type %>
        <%= f.select :resource_type, Resource.resource_types.keys.collect {|u| [u.titleize, u]},class:"form-control"%>
    </div>
    <div class="form-group">
        <%= f.label :card_layout_id %>
        <%= f.select :card_layout_id, @layout_options, class:"form-control"%>
    </div>
    <button type="submit" >Upload</button>
    <ul>
        <% @resources.each do |resource| %>
            <li><%= link_to " Delete: [#{resource.id}]", drop_resource_path(id: resource.id ), method: :delete, remote: true %></li>
        <% end %>
    </ul>
<% end %>