config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index", page: :home
  get :privacy, to: "pages#index", page: :privacy

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  delete :logout, to: "sessions#destroy"
  get :layouts, to: "card_layouts#index"
  post "layout/change", to: "card_layouts#change"
  post :add, to: "resources#add"
  get :upload, to: "upload#index"
  delete :drop_resource, to: "upload#drop_resource"
  
  resources :shares do
    get :story
  end

  resources :cards do
    post :generate
    post :detach_music
    get :thumb
  end

  resources :resources do
    post :upload, on: :collection
    post :load, on: :collection
    post :insert, on: :collection
  end
end

app/views/shared/_normal_navigation.html.erb
<div class="navbar navbar--top <%= params[:action] %>">
    <div class="container-fluid px-5">
        <div class="logo-container">
            <%= link_to root_path do %>
                <% #= image_tag "bauble.png", class: "logo-top-anchor" %>
                <%= image_tag "logo_gradient.png", class: "logo" %>
            <% end %>
        </div>
        <div class="editor--top_menu"><a class="drop jsObjectDropAction hiden"><i class="ti-trash"></i></a></div>
        <div class="navbar__menu--right navbar-expand">
            <% if editor %>
                <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
                    <li class="nav-item jsSaveProgress jsSaveProgress-<%= @card.id if @card.present? %> <%= "hidden" if @card.nonqueue? || @card.render_status.nil? %>">
                        <a href="<%= @card.url if @card.success? %>" class="progress mx-auto progress--circle-<%= @card.id if @card.present? %>" <%= "download" if @card.success? %>>
                            <span class="progress-left">
                                <span class="progress-bar border-primary"></span>
                            </span>
                            <span class="progress-right">
                                <span class="progress-bar border-primary"></span>
                            </span>
                            <div class="progress-value w-100 h-100 rounded-circle d-flex align-items-center justify-content-center jsDownloadVideo">
                                <div class="small jsProgressText-<%= @card.id %>">
                                    <% if @card.success? %>
                                        <i class="ti-download"></i>
                                    <% end %>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item dropdown action jsSave">
                        <a class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" id="saveAction">
                            <i class="ti-save"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="saveAction" >
                            <%= link_to card_generate_path(@card), class:"dropdown-item", data: {"layout-id": @layout.try(:id), "user-id": @current_user.try(:id)}, method: :post, remote: true do %>
                            <i class="ti-video-clapper"></i> ビデオを保存する
                            <% end %>
                            <a class="dropdown-item jsActionSaveImage" data-cid="<%= "#{@current_user.name}_card_#{@card.id}_" %>""><i class="ti-image"></i> JPGを保存する</a>
                        </div>
                    </li>
                    <li class="nav-item action jsShare">
                        <a class="nav-link">
                            <i class="ti-share"></i>
                        </a>
                        <!--div class="dropdown-menu dropdown-menu-right" aria-labelledby="shareAction" >
                            <a class="dropdown-item jsFacebookShare" href="/"><i class="ti-facebook"></i> Facebook</a>
                            <a class="dropdown-item jsTweet" href="/"><i class="ti-twitter"></i> Twitter</a>
                        </div-->
                    </li>
                </ul>
            <% else %>
                <ul class="user--menu dropdown">
                    <a class="avatar-wrapper" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="dropdownMenuLink">
                        <%= image_tag @current_user.picture, class:"avatar" %>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink" >
                        <a class="dropdown-item" href="/"><%= @current_user.name %></a>
                        <a class="dropdown-item" href="/">カード管理</a>
                        <div class="dropdown-divider"></div>
                        <%= link_to "ログアウト", logout_path, class:"dropdown-item", method: :delete%>
                    </div>
                </ul>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/_toast.html.erb
<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <strong class="mr-auto">Info</strong>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="toast-body">
    機能をかいはつしています。
  </div>
</div>