config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index", page: :home
  get :privacy, to: "pages#index", page: :privacy

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  delete :logout, to: "sessions#destroy"
  get :layouts, to: "card_layouts#index"
  post "layout/change", to: "card_layouts#change"
  post :add, to: "resources#add"
  get :upload, to: "upload#index"
  delete :drop_resource, to: "upload#drop_resource"
  
  resources :shares do
    get :story
  end

  resources :cards do
    post :generate
    post :detach_music
    get :thumb
  end

  resources :resources do
    post :upload, on: :collection
    post :load, on: :collection
    post :insert, on: :collection
  end
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :card_layout
    belongs_to :user
    belongs_to :music, class_name: "Resource", foreign_key: 'music_resource_id', optional: true
    enum render_status: [:nonqueue, :pending, :inprogress, :failed, :success]
    after_initialize :set_default_status, if: :new_record?

    def set_default_status
        self.render_status ||= :nonqueue
    end
end

app/controllers/cards_controller.rb
class CardsController < BaseNavigationController
    def index
        @cards = @current_user.cards
    end

    def create
        @card = Card.new card_layout_id: params[:layout_id], user_id: params[:uid]
        return unless @card.save
    end

    def edit
        @card = Card.find_by id: params[:id]
        @layout = @card.card_layout
        @layouts = CardLayout.all
        @resource = Resource.new
    end

    def update
        @card = Card.find_by id: params[:id]
        if @card.present?
            @card.update_attributes format: params[:format], thumb: params[:thumb]
        end
    end

    def generate
        @card = Card.find_by id: params[:card_id]
        return unless @card.music.present?
        if @card.code.nil?
            expi = 5.day.from_now
            share_name = Digest::SHA1.hexdigest("#{@card.user_id}|#{@card.id}|#{expi}")
            @card.update_attributes expired: expi, code: share_name
        end
        if @card.present? && (@card.success? || @card.nonqueue?)
            @card.update_attributes render_status: :pending
            VideoRenderWorker.perform_async(@current_user.id, @card.id)
        end
    end

    def thumb
        card = Card.find_by id: params[:card_id]
        respond_to do |format|
            format.png { send_data(Base64.decode64(card.thumb.gsub('data:image/png;base64,','')), {type: "image/png", disposition: "inline"})}
        end
    end

    def detach_music
        @card = Card.find_by id: params[:card_id]
        return unless @card.music.present?
        @card.update_attributes music_resource_id: nil
    end

    def destroy
        @card = Card.find_by id: params[:id]
        if @card.present?
            @card.destroy
            redirect_to cards_path
        end
    end
end

app/views/cards/_holder_text.html.erb
<div class="holder_text"><span>新しいエレメントをえらんでください！</span></div>

app/views/cards/_music_edit.html.erb
<div class="music--edit-container <%= "hiden" if card.music.nil? %> row p-0 m-0">
    <div class="col-lg-12 align-items-center justify-content-center">
        <div class="progress-info col-lg-12">
            <div class="audio-player">
                <audio>
                    <source class="jsAudioSource" src="<%= card.try(:music).try(:container).try(:url) %>" type="audio/mp3" />
                </audio>
            </div>
        </div>
    </div>
    <%= link_to card_detach_music_path(card), class:"align-items-center justify-content-center detach-music-action", method: :post, remote: true do %>
        <i class="ti-close"></i>
    <% end %>
</div>

app/views/cards/create.js.erb
<% if @card.present? %>
    window.location = '<%= edit_card_path(@card) %>'
<% end %>

app/views/cards/detach_music.js.erb
$('.music--edit-container').addClass("hiden")

app/views/cards/edit.html.erb
<div class="editor__wrapper">
    <div class="side__bar--wrapper flex-row">
        <div class="element-selector">
            <ul class="nav flex flex-column">
                <li class="nav-item dropright top_menu">
                    <a class="nav-link add__more--resources text-center" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Add more resources"><i class="ti-plus"></i></a>
                    <div class="dropdown-menu">
                        <%= link_to add_path(add: :image), class:"dropdown-item", method: :post, remote: true do %>
                            <i class="ti-gallery"></i> 画像
                        <% end %>
                        <%= link_to add_path(add: :sticker), class:"dropdown-item", method: :post, remote: true do %>
                            <i class="ti-face-smile"></i> ステッカー
                        <% end %>
                        <%= link_to add_path(add: :text), class:"dropdown-item", method: :post, remote: true do %>
                            <i class="ti-text"></i> 文字
                        <% end %>
                        <%= link_to add_path(add: :music), class:"dropdown-item", method: :post, remote: true do %>
                            <i class="ti-music"></i> 音楽
                        <% end %>
                        <%= link_to load_resources_path(user_id: @current_user.id), class:"dropdown-item", method: :post, remote: true do %>
                            <i class="ti-upload"></i> アプロード
                        <% end %>
                    </div>
                </li>
                <li class="nav-item">
                    <%= link_to add_path(add: :layout), class:"nav-link component__select", title:"Change style", method: :post, remote: true do %>
                        <i class="ti-layout"></i>
                    <% end %>
                </li>
                <!--li class="nav-item">
                    <a class="nav-link component__select" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Change size"><i class="ti-layers-alt"></i></a>
                </li-->
            </ul>
        </div>
        <div class="element-detail">
            <%= render partial: "resources/list_layout", locals:{layouts: @layouts} %>
        </div>
    </div>
    <div class="card--editor" data-card-id="<%= @card.id %>" data-card-format="<%= @card.format.to_json %>" data-lyt="<%= {width: @layout.width, height: @layout.height, ratio: @layout.ratio}.to_json %>">
        <div class="canvas">
            <canvas class="content--place" id="edit__content--place" width="<%= @layout.width*@layout.ratio %>" height="<%= @layout.height*@layout.ratio %>">
        </div>
    </div>
    <%= render partial:"music_edit", locals: { card: @card } %>
</div>
<%= render partial: "resources/upload_resource", locals:{resource: @resource, card: @card} %>
<%= render partial: "shares/share_link_dialog", locals:{ card: @card } %>

app/views/cards/generate.js.erb
<% unless @card.music.present? %>
alert('先に音楽を挿入してください')
<% end %>

app/views/cards/index.html.erb
<div class="card-list container">
    <div class="row">
        <div class="col-md-3 mb-2">
            <%= link_to cards_path(layout_id: 1, uid: @current_user.id), class:"link", remote: true, method: :post do %>
            <div class="card add-new-card py-2">
                <div class="plus-button"><i class="ti-plus"></i></div>
            </div>
            <% end %>
        </div>
        <% @cards.each do |card| %>
            <div class="col-md-3 mb-2">
                <div class="card">
                    <div class="card-top">
                        <div class="card-img-top" style="background: url(<%= card.thumb.nil? ? asset_url("thumbnail.png") : "#{card_thumb_url(card)}.png" %>)"></div>
                        <img class="thumb" src="<%= card.thumb.nil? ? asset_url("thumbnail.png") : "#{card_thumb_url(card)}.png" %>"/>
                        <div class="top-menu">
                            <div class="menu-anchor">
                                <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" id="editAction"><i class="ti-more"></i></a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="editAction" >
                                    <%= link_to edit_card_path(card), class:"dropdown-item", data: { turbolinks: false } do %><i class="ti-wand"></i> 編集<% end %>
                                    <%= link_to card_path(card), class:"dropdown-item", method: :delete, data: { confirm: '同意しませんか?' } do %>
                                        <i class="ti-trash"></i> 削除
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="progress progress-<%= card.id %> <%= "hidden" unless (card.inprogress? || card.pending?) %>">
                        <div class="progress-bar bg-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <!--div class="card-body">
                        <span class="card-title">Card name</span>
                    </div-->
                </div>
            </div>
        <% end %>
    </div>
</div>
<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <img class="rounded mr-2" alt="...">
    <strong class="mr-auto">Bootstrap</strong>
    <small>11 mins ago</small>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="toast-body">
    Hello, world! This is a toast message.
  </div>
</div>
<script>
// $(document).ready(function(params) {
//     $('.toast').toast('show')
// })
</script>